import { describe, expect, it } from 'vitest';
import { OPS } from 'pdfjs-dist/legacy/build/pdf.mjs';
import type { PDFDocumentProxy, PDFPageProxy } from 'pdfjs-dist/types/src/display/api';
import { SAMPLES, getSample, type SampleId } from '../../src/lib/sample-documents';
import { createPageGeometry, pageToDisplay } from '../../src/lib/coordinates';
import { destroyDocument, loadPdfBytes } from '../../src/lib/pdf-loader';
import { NODE_PDFJS_PARAMS, nodeGetDocument } from './pdfjs-node';

async function open(id: SampleId): Promise<PDFDocumentProxy> {
  const sample = getSample(id);
  const result = await loadPdfBytes(nodeGetDocument, { name: sample.fileName, type: 'application/pdf' }, await sample.build(), NODE_PDFJS_PARAMS);
  if (!result.ok) throw new Error(`Sample ${id} failed to open: ${result.error}`);
  return result.value.pdf;
}

async function pages(pdf: PDFDocumentProxy): Promise<PDFPageProxy[]> {
  return Promise.all(Array.from({ length: pdf.numPages }, (_, i) => pdf.getPage(i + 1)));
}

/** MediaBox is not exposed by PDF.js, so read it from the generated bytes via pdf-lib. */
async function mediaBoxes(bytes: Uint8Array): Promise<number[][]> {
  const { PDFDocument } = await import('pdf-lib');
  const doc = await PDFDocument.load(bytes);
  return doc.getPages().map((p) => {
    const b = p.getMediaBox();
    return [b.x, b.y, b.x + b.width, b.y + b.height];
  });
}

describe('sample documents (sample-documents spec)', () => {
  it('offers the three named samples', () => {
    expect(SAMPLES.map((s) => s.title)).toEqual(['Academic Research Paper', 'Invoice', 'Technical Spec']);
  });

  it('academic paper is multi-page', async () => {
    const pdf = await open('academic-paper');
    expect(pdf.numPages).toBeGreaterThan(1);
    await destroyDocument(pdf);
  });

  it('invoice has an image operator and a tinted (non-white) fill', async () => {
    const pdf = await open('invoice');
    const page = await pdf.getPage(1);
    const ops = await page.getOperatorList();
    expect(ops.fnArray).toContain(OPS.paintImageXObject);
    const fills = ops.fnArray
      .map((fn, i) => (fn === OPS.setFillRGBColor ? ops.argsArray[i] : null))
      .filter((a): a is unknown[] => a !== null)
      .map((a) => String(a[0]).toLowerCase());
    expect(fills.some((c) => c !== '#ffffff' && c !== '#1f2a3b' && c.startsWith('#d'))).toBe(true);
    await destroyDocument(pdf);
  });

  it('technical spec has a /Rotate 90 page and a page whose CropBox differs from its MediaBox', async () => {
    const sample = getSample('tech-spec');
    const bytes = await sample.build();
    const pdf = await open('tech-spec');
    const all = await pages(pdf);
    expect(all.some((p) => p.rotate === 90)).toBe(true);
    const media = await mediaBoxes(bytes);
    expect(all.some((p, i) => JSON.stringify(p.view) !== JSON.stringify(media[i]))).toBe(true);
    await destroyDocument(pdf);
  });

  it('samples use serif, sans and mono in regular and bold', async () => {
    const fonts = new Set<string>();
    for (const id of ['academic-paper', 'tech-spec'] as const) {
      const pdf = await open(id);
      for (const page of await pages(pdf)) {
        const content = await page.getTextContent();
        for (const style of Object.values(content.styles)) fonts.add(style.fontFamily);
      }
      await destroyDocument(pdf);
    }
    expect([...fonts]).toEqual(expect.arrayContaining(['serif', 'sans-serif', 'monospace']));
  });
});

describe('deterministic output (4.2)', () => {
  it.each(SAMPLES.map((s) => [s.id] as const))('%s generates byte-identical PDFs', async (id) => {
    const sample = getSample(id);
    const a = await sample.build();
    const b = await sample.build();
    expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true);
  });
});

describe('coordinates.ts agrees with PDF.js PageViewport (4.3)', () => {
  it.each(SAMPLES.map((s) => [s.id] as const))('%s: every page within 1e-6 pt', async (id) => {
    const pdf = await open(id);
    for (const page of await pages(pdf)) {
      const viewport = page.getViewport({ scale: 1 });
      const [x0, y0, x1, y1] = page.view as [number, number, number, number];
      const geometry = createPageGeometry([x0, y0, x1, y1], page.rotate);
      for (const [x, y] of [[x0, y0], [x1, y1], [x0 + 100, y1 - 92], [(x0 + x1) / 2, y0 + 13]] as const) {
        const [vx, vy] = viewport.convertToViewportPoint(x, y);
        const d = pageToDisplay(geometry, { x, y });
        expect(Math.abs(d.x - vx)).toBeLessThan(1e-6);
        expect(Math.abs(d.y - vy)).toBeLessThan(1e-6);
      }
    }
    await destroyDocument(pdf);
  });
});
